export const optionsType = [
    { value: '', label: 'Todos os tipos' },
    { value: 'normal', label: 'Normal' },
    { value: 'fighting', label: 'Lutador' },
    { value: 'flying', label: 'Voador' },
    { value: 'poison', label: 'Venenoso' },
    { value: 'ground', label: 'Terrestre' },
    { value: 'rock', label: 'Pedra' },
    { value: 'bug', label: 'Inseto' },
    { value: 'ghost', label: 'Fantasma' },
    { value: 'steel', label: 'Aço' },
    { value: 'fire', label: 'Fogo' },
    { value: 'water', label: 'Água' },
    { value: 'grass', label: 'Grama' },
    { value: 'electric', label: 'Elétrico' },
    { value: 'psychic', label: 'Psíquico' },
    { value: 'ice', label: 'Gelo' },
    { value: 'dragon', label: 'Dragão' },
    { value: 'dark', label: 'Sombrio' },
    { value: 'fairy', label: 'Fada' },
];
